### PR TITLE
Add as an extension to Web UI

### LINKED ISSUE #13: Feature Request - Add this as an extension to Web UI
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Developing-extensions

This would be awesome as an extension to be able to check for updates

### PR DESCRIPTION
**Pull request by Kilvoctu**
Will close #13

As mentioned [in webui discussion here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/4828#discussioncomment-4182629), it does appear to be as simple as shuffling files around.  

A scripts folder was created, and "stylepile.py" was placed inside of it.
On lines 369 and 370, the code seems to look at the full filepath to the example images. I considered making these relative paths, but instead I just corrected the filepath.

sidenotes:
I added .gitignore and included .idea, if you decide to use PyCharm. Also a .gitignore could be useful otherwise anyway
The last line of your code (572) is unreachable because right above it is a return statement. I put it above the return statement.

For testing, I cloned my fork into the /extensions folder, then generated an image, then another using StylePile
image
The examples loaded up in the script and I seem to be able to use the other UI elements, but further testing should probably be done.

### CODE REVIEW

**Comment by some9000** [comment]
Thanks for helping!
Now there's this tiny little thing - the [beta branch](https://github.com/some9000/StylePile/tree/Beta-2.0) that was linked in the discussion is quite a bit ahead of this version. I tried to move it into folders and sort the variables same way it is done here. But, for whatever reason it just isn't showing up. It is in the list, but in now way in the UI...

**Comment by Kilvoctu** [comment]
I can take a look at it in a moment after finishing up a thing on my bot. Forgot there was two branches 😂

**Comment by Kilvoctu** [comment]
I did it for your beta branch and it's still working for me. Same steps, I can PR this one too if you want, but you probably already did the same things.
https://github.com/Kilvoctu/StylePile/tree/extension-b

It didn't show up in the Web UI at first for me. I had to "restart gradio and refresh components" under settings, then for good measure I hit "apply and restart ui" under extensions. After that it did appear in the scripts dropdown.
I clicked on each of the StylePile tabs and generated a "Grim" "Cel Shaded" car, and it seemed to work (I confirm by checking the PNG info).

**Comment by some9000** [comment]
Thanks! Finally cleaned up my code. Had a single definition of an element for some button press testing and that, apparently, killed everything. Now it works. Phew, one down, lots to go.

**Pull request merged**
